-- ==========================================
-- Migration: Add thumbnail_url to versions
-- Date: 2026-04-21
-- Description: Stores the JPEG preview frame generated by ffmpeg at upload.
--              Enables instant first paint (<video poster>) and list thumbnails.
-- ==========================================

ALTER TABLE "versions" ADD COLUMN IF NOT EXISTS "thumbnail_url" TEXT;
